config/routes.rb
Rails.application.routes.draw do
  
  get 'cart/index'

  resources :categories
  get 'pages/index'

      devise_for :users
  root to: "items#index"

  resources :items
  resources :recordings
  root "items#index"
  
  get '/help', to: 'static_pages#help'

  get 'static_pages/profile'

  get '/catalog', to: 'items#index'

  get '/search', to: 'static_pages#search'

  get '/cart', to: 'cart#index'
  get '/cart/clear', to: 'cart#clearCart'
  get '/cart/:id', to: 'cart#add'
  
  get '/cart/remove/:id' => 'cart#remove'
  
  get 'static_pages/checkout'

  get 'static_pages/confirmation'

   post '/search' => 'static_pages#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :recordings, dependent: :destroy
       mount_uploader :avatar, AvatarUploader
       mount_uploader :song, MusicUploader
       serialize :audioarray, Array
     
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index

    @items = Item.order(genre: :asc).all

  end



  # GET /items/1
  # GET /items/1.json
  def show
   # @item.audioarray
  end
  

  # GET /items/new
  def new
     @categories = Category.all
      @objArray = Array.new
 @categories.each do |cat|
   @objArray << cat.title 
  end
    
    if user_signed_in? && current_user.email?
    @item = Item.new(:owner => current_user.email)
    @item.save
  else
     @item = Item.new
  end

   # @item.audioarray
  #  <%= @recording  %>
   # @recording = Recording.new
  #  5.times { @item.recordings.build }
  #  @recordings = @item.recordings.all
  end

  # GET /items/1/edit
  def edit
    @categories = Category.all
   @objArray = Array.new
 @categories.each do |cat|
   @objArray << cat.title
 end
#  @recordings = @items.recordings.build(:upsongs => audiotar) 
#  @recordings.save
  end

  # POST /items
  # POST /items.json
  def create
  
    
    @item = Item.new(item_params)

#  @recordings = @items.recordings.build(:upsongs => audiotar) 
#  @recordings.save

    #  5.times { @item.recordings.build() }
    respond_to do |format|
      if @item.save
     
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:avatar, :song, :audiotar, :audioarray ,:myarray, :owner, :music, :artist, :title, :price, :image_url, :genre, :label, :year)
    end
end

app/helpers/items_helper.rb
module ItemsHelper

     

    def options_for_genre
        @objArray
    end


  
  
def mobile_device?
  if session[:mobile_param]
    session[:mobile_param] == "1"
  else
    request.user_agent =~ /Mobile|webOS/
  end
end

end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true, html: {multipart: true} ) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="jumbotron">
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-block">

     
       <div class="card-img-top">  
          <%= image_tag(item.avatar_url) if item.avatar? %>
          <br>
          <p class="card-text">
          <div class="btn btn-sm"><%= form.file_field :avatar %></div>
          <%= form.hidden_field :avatar_cache %>
            </p>
         </div>
       
      </div>
    </div>
  </div>
<div class="col-sm-6">
 <div class="form-group">
    <%= form.label :artist, class: "form-label" %>
    <%= form.text_field :artist, class: "form-control" %>

</div>
 <div class="form-group">
   <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
 <div class="form-group">
   <%= form.label :price, class: "form-label" %>
    <%= form.text_field :price, class: "form-control" %>
  </div>


<div class="form-group">
  <label for="sel1">Genre:</label>
<%= form.select :genre, options_for_select([
  ["#{item.genre if item.genre?}", ""], 
  "Rock", 
  "Pop", 
  "Classical", 
  "Folk", 
  "Jazz", 
  "Blues", 
  "Punk", 
  "Techno", 
  "Heavy Metal",
  "Hip Hop", 
  "Reggae", 
  "Rhythm and Blues", 
  "Opera", 
  "Rap", 
  "Soul", 
  "Disco", 
  "House", 
    "Gospel", 
  "Orchestra", 
  "Rap", 
  "Indy", 
  "Electronic", 
  "Grunge",
  "Alternative" ]), 
  {}, { class: "form form-group form-control" } %>
</div>


 <div class="form-group">
   <%= form.label :label, class: "form-label" %>
    <%= form.text_field :label, class: "form-control" %>
  </div>

 <div class="form-group">
   <%= form.label :year, class: "form-label" %>
    <%= form.text_field :year, class: "form-control" %>
  </div>


    <div class="track"><h4>Sample Track</h4>
  
       <div class="form-group">
            <div class="field">
             
        
               <div class="form-group">
                     <div class="field">
                         <div class="btn btn-sm"><%= form.file_field :song %></div>
                          <%= form.hidden_field :song_cache %>
                       
                    </div>
                </div>
        
               
             </div>
         </div>
    </div>
    <div class="actions">
    <%= form.submit %>
  </div>

</div>
  </div>

<% end %>

app/views/items/edit.html.erb
<%= render 'form', item: @item %>

<button class="btn btn-success btn-sm"><%= link_to 'Show', @item %></button>
<button class="btn btn-primary btn-sm" style="margin-left:5em"><%= link_to 'Back', items_path %></button>

 

app/views/items/index.html.erb
<% provide(:title, "Catalog") %>
<p id="notice"><%= notice %></p>

<h1>Catalogue</h1>


<%= form_with(model: @item, local: true, html: {multipart: true} ) do |f| %>
 <div class="form-group">
<%= f.select(:user_select, [  "Genre", "Artist", "Title", "Year"  ], {}, { :method => 'onchange_handler()'} ) %>
</div>
<% end %>



<%  num_cols = 4 %>

<% if mobile? %><!--  mobile helper method in application controller  -->
<%  num_cols = 2 %>
<% end %>
<% @items.each_slice(num_cols) do |row| %>
    <div class="row"> 

       <% row.each do |item| %>
         
       
          <% if mobile? %>
            <div class="col-sm-6">
            <%  else %>
            <div class="col-sm-3">
          <% end %>
      
            <div class="card">
              <img class="card-img-top" src= <%= item.avatar_url  %> alt="Card image">
              <div class="card-body">
                <h4 class="card-title"><%= item.artist %></h4>
                <h5 class="card-text"><%= item.title %></h5>
                <p class="card-text">€ <%=item.price %></p>
          
                  <button class="btn btn-success btn-sm"><%= link_to 'Show', item %></button>
          
                <% if current_user && item.owner == current_user.email or  current_user && current_user.admin %>
                   <button class="btn btn-primary btn-sm"><%= link_to 'Edit', edit_item_path(item) %></button>
                   <button class="btn btn-danger btn-sm"><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></button>
              <% elsif current_user %>
                   <button class="btn btn-default btn-sm"><a href="/cart/<%= item.id %>">Add to Cart</a></button>
                  
                <% end %>
                 
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </br>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<h2><%= @item.artist %></h2>

<div class="jumbotron">
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-block">

      <img class="img-thumbnail" alt="Card image cap" src = <%= @item.avatar_url  %> >
      </div>
    </div>
  </div>
  <div class="col-sm-6">
      <table class="table table-striped table-responsive">
    <thead>
      <tr>
        <th>Artist</th>
        <th>Title</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @item.artist %></td>
        <td><%= @item.title %></td>
      </tr>
      </tbody>
      <thead>
      <tr>
        <th>Year</th>
        <th>Label</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @item.year %></td>
        <td><%= @item.label %></td>
      </tr>
      
   </br>
    </tbody>
          <thead>
      <tr>
        <th>Genre</th>
        <th>Price</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @item.genre %></td>
        <td><%= @item.price %></td>
      </tr>
      
   </br>
    </tbody>
   </table>
    </br>   </br>
    <div class="track">
    <h4>Sample Track</h4>
          <audio controls>
            <source src= <%=  @item.song  %> >
          </audio>

   </br>   </br>

  

       
        <% if current_user && @item.owner == current_user.email %>
            <button class="btn btn-success btn-sm" ><%= link_to 'Edit', edit_item_path(@item) %></button>
        <% elsif current_user %>
            <button class="btn btn-default btn-sm"><a href="/cart/<%= @item.id %>">Add to Cart</a></button>
        <% end %>
        
         <button class="btn btn-primary btn-sm" style="margin-left:5em"><%= link_to 'Back', :back %></button>
</div>
  </div>
</div>
</div>