config/routes.rb
Rails.application.routes.draw do
  
  get 'cart/index'

  resources :categories
  get 'pages/index'

      devise_for :users
  root to: "items#index"

  resources :items
  resources :recordings
  root "items#index"
  
  get '/help', to: 'static_pages#help'

  get 'static_pages/profile'

  get '/catalog', to: 'items#index'

  get '/search', to: 'static_pages#search'

  get '/cart', to: 'cart#index'
  get '/cart/clear', to: 'cart#clearCart'
  get '/cart/:id', to: 'cart#add'
  
  get '/cart/remove/:id' => 'cart#remove'
  
  get 'static_pages/checkout'

  get 'static_pages/confirmation'

   post '/search' => 'static_pages#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @selected= Category.find(params[:id])
  #  @items = Item.all

    @items = Item.where("genre like ?", @selected.title)
 # @items = Item.all.where(params[:genre])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @categories = Category.all
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :description, :image)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
    
    
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="jumbotron mydevise">
     <br>
 <div class="form-group">
<div class="form-group">
  <label for="sel1">Genre:</label>
<%= form.select :title, options_for_select([
  ["Select One", ""], 
  "Rock", 
  "Pop", 
  "Classical", 
  "Folk", 
  "Jazz", 
  "Blues", 
  "Punk", 
  "Techno", 
  "Heavy Metal",
  "Hip Hop", 
  "Reggae", 
  "Rhythm and Blues", 
  "Opera", 
  "Rap", 
  "Soul", 
  "Disco", 
  "House", 
    "Gospel", 
  "Orchestra", 
  "Rap", 
  "Indy", 
  "Electronic", 
  "Grunge",
  "Alternative" 
  ]), 
  {}, { class: "form form-group form-control" } %>
</div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :category_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :category_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% provide(:title, "Categories") %>
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<% @categories.each_slice(3) do |row| %>
  <div class="row"> 

     <% row.each do |category| %>
     <div class="col-sm-4">

<div class="panel panel-default category ">
  <div class="panel-body ">

     <h4><div class="genre_title"><%= category.title %></div></h4>
      <br>
         <button class="btn btn-success btn-sm"><%= link_to 'Show', category %></button>
    <% if current_user && current_user.admin %>
        <button class="btn btn-primary btn-sm" style="margin-left:5em"><%= link_to 'Edit', edit_category_path(category) %></button>
        <button class="btn btn-danger btn-sm" style="margin-left:5em"><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></button>
    <% end %>
    </div>
  </div>


</div>
<% end %>
</div>
</br>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @selected.title %></h1>

<% @items.each_slice(3) do |row| %>

    <div class="row"> 
  
       <% row.each do |item| %>
       
          <% if item.genre? && item.genre == @selected.title %>
          
                    <div class="col-sm-4">
                      <div class="card">
                        <img class="card-img-top" src= <%= item.avatar_url  %> alt="Card image">
                        <div class="card-body">
                          <h4 class="card-title"><%= item.artist %></h4>
                          <h5 class="card-text"><%= item.title %></h5>
                          <p class="card-text">€ <%=item.price %></p>
                    
                            <button class="btn btn-success btn-sm"><%= link_to 'Show', item %></button>
                    
                          <% if current_user && item.owner == current_user.email or current_user && current_user.admin %>
                             <button class="btn btn-primary btn-sm"><%= link_to 'Edit', edit_item_path(item) %></button>
                             <button class="btn btn-danger btn-sm"><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></button>
                          <% end %>
                        </div>
                      </div>
                    </div>
          <% end %>
      <% end %>
    </div>
  </br>
<% end %>
<button class="btn btn-primary btn-sm"><%= link_to 'Back', categories_path %></button>