config/routes.rb
Rails.application.routes.draw do
  
  get 'cart/index'

  resources :categories
  get 'pages/index'

      devise_for :users
  root to: "items#index"

  resources :items
  resources :recordings
  root "items#index"
  
  get '/help', to: 'static_pages#help'

  get 'static_pages/profile'

  get '/catalog', to: 'items#index'

  get '/search', to: 'static_pages#search'

  get '/cart', to: 'cart#index'
  get '/cart/clear', to: 'cart#clearCart'
  get '/cart/:id', to: 'cart#add'
  
  get '/cart/remove/:id' => 'cart#remove'
  
  get 'static_pages/checkout'

  get 'static_pages/confirmation'

   post '/search' => 'static_pages#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_categories.html.erb
<h1>Categories</h1>

<br>

<table class="catalog">
    
    <% @categories.each do |category| %>
    
        <tr>
            <td>
                <div class="category">
                    <p><%= category.title %></p>
                </div>
            </td>
        </tr>
            
    <% end %>
    
</table>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Good Vibrations Vinyl 2017
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse metal_header">
  <div class="container">
    <h4 id="logo">Good Vibrations Vinyl</h4>
    <nav>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   catalog_path %></li>
            <li><%= link_to "Browse", categories_path %></li>
            <li><%= link_to "Search", search_path %></li>
            
            <li><%= link_to "Shopping Cart", cart_path %></li>

        <% if user_signed_in? %>
        
           <% if session[:cart] then %>
             <div class="image_header"><%= link_to image_tag("cart_icon.png", alt:"cart Image"), cart_path %></div>
           <% end %>
           
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.username %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'New Item', new_item_path %></li>
              <li><%= link_to 'New Category', new_category_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
 </div>
</header>

app/views/layouts/_search.html.erb
<div class="search_form">
          <%= form_tag("/search",  :method=> 'post') do %>
          <%= text_field_tag :q, params[:q], placeholder: "Search", class:"form-control"%>
          <%= submit_tag 'Search', class: 'btn btn-success form-control' %>
          <% end %>

</div>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | GoodVibrationsVinyl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <div class="container">
    <%= yield %>
    </div>
  <%=render 'layouts/footer'%> 
  </body>
</html>